name: sonarqube  # Name of the workflow

# Define when this workflow should run.
# You can uncomment the 'on' block below to specify conditions for automatic runs,
# or leave it as is for manual runs using 'workflow_dispatch'.

# on:
#   push:
#     branches:
#       - "master"
#     paths:
#       - "packer/aws/sonarqube/**"
#       - "scripts/sonarqube.sh"

on: workflow_dispatch  # Allowing manual runs using 'workflow_dispatch'

jobs:
  ami-creation:
    name: Sonarqube AMI creation  # Name of the job
    runs-on: ubuntu-22.04  # Operating system for the job

    steps:
      - name: Configure AWS Credentials  # Step for configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Test configuration of AWS CLI  # Step to check AWS CLI configuration
        run: |
          aws --version
          aws configure list | grep region | awk '{print $2}'

      - name: Checkout  # Step to checkout the repository
        uses: actions/checkout@v2 

      - name: Setup `packer`  # Step to set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.5"  # Packer version

      - name: Run `packer init`  # Step to run 'packer init'
        id: init
        run: "packer init ./packer/aws/sonarqube/"

      - name: Run `packer validate`  # Step to run 'packer validate'
        id: validate
        run: "packer validate ./packer/aws/sonarqube/"

      - name: Run `packer build`  # Step to run 'packer build'
        id: build
        run: "packer build ./packer/aws/sonarqube/"
